# Fonte
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.5

# Padding
window_padding_width 12

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Scroll
scrollback_lines 10000

# Mouse
copy_on_select yes

# Janela
confirm_os_window_close 0
remember_window_size yes

# Transparência
background_opacity 0.92
dynamic_background_opacity no
inactive_text_alpha 1.0

# Bell
enable_audio_bell no

# Performance
sync_to_monitor yes

# Cores geradas pelo template oficial do Noctalia.
globinclude themes/noctalia.conf

# Use the login shell registered for the user (no shell override).

# Abas
map f2 set_tab_title
map ctrl+shift+t new_tab_with_cwd

# Sessões
# Pressione F7 e, em seguida, a segunda tecla do atalho.
map f7>s save_as_session --use-foreground-process --base-dir ~/.local/share/kitty/sessions
map f7>o goto_session ~/.local/share/kitty/sessions
map f7>p goto_session -1
