# Fonte
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.5

# Padding
window_padding_width 12

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Scroll
scrollback_lines 10000

# Mouse
copy_on_select yes

# Janela
confirm_os_window_close 0
remember_window_size yes

# Transparência
background_opacity 0.92

# Bell
enable_audio_bell no

# Performance
sync_to_monitor yes

# Cores (temporárias)
# include current-theme.conf

# Use the login shell registered for the user (no shell override).
